/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminInterfaces;

import DBCONNECT.db_connect1;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class update_member extends javax.swing.JFrame {

   
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    update_mem um2 = new update_mem();
    
    public update_member() {
        initComponents();
        
        con = db_connect1.connect();
        
        this.get_val();
    }
    
        private void get_val(){
        String sql = "SELECT M.fname,M.sname,M.dob,M.email,M.telephone,LM.username,LM.password FROM member M,login_member LM WHERE M.id = '"+um2.get_id()+"' AND LM.mem_no = '"+um2.get_id()+"' ";
        
        try{
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            rs.next();
            f_name_box.setText(rs.getString("fname"));
            l_name_box.setText(rs.getString("sname"));
            dob_box.setText(rs.getString("dob"));
            
            email_box.setText(rs.getString("email"));
            tele_box.setText(rs.getString("telephone"));
           
            username_box.setText(rs.getString("username"));
            password_box.setText(rs.getString("password"));
        }
        catch(Exception e){
            System.out.println("Error in reading member and login_member tables. Error = "+e.getMessage());
        }
    }
        
        private void update_data(){
        char[] pass = password_box.getPassword();

        String password = new String(pass);
        String sql = "UPDATE member SET fname = '"+f_name_box.getText()+"',sname = '"+l_name_box.getText()+"',dob = '"+dob_box.getText()+"',email = '"+email_box.getText()+"',telephone = '"+tele_box.getText()+"' WHERE id = '"+um2.get_id()+"'";
        String sql_1 = "UPDATE login_member SET username = '"+username_box.getText()+"',password = '"+password+"' WHERE mem_no = '"+um2.get_id()+"'"; 
        try{
            ps = con.prepareStatement(sql);
            ps.execute();
            ps = con.prepareStatement(sql_1);
            ps.execute();
        }
        catch(Exception e){
            System.out.println("Error to update row. Error = "+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f_name_box = new javax.swing.JTextField();
        l_name_box = new javax.swing.JTextField();
        email_box = new javax.swing.JTextField();
        tele_box = new javax.swing.JTextField();
        dob_box = new javax.swing.JTextField();
        username_box = new javax.swing.JTextField();
        password_box = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 540));
        getContentPane().setLayout(null);

        f_name_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                f_name_boxKeyTyped(evt);
            }
        });
        getContentPane().add(f_name_box);
        f_name_box.setBounds(180, 110, 200, 30);

        l_name_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                l_name_boxKeyTyped(evt);
            }
        });
        getContentPane().add(l_name_box);
        l_name_box.setBounds(180, 160, 200, 30);
        getContentPane().add(email_box);
        email_box.setBounds(180, 210, 200, 30);

        tele_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tele_boxKeyTyped(evt);
            }
        });
        getContentPane().add(tele_box);
        tele_box.setBounds(180, 260, 200, 30);
        getContentPane().add(dob_box);
        dob_box.setBounds(180, 310, 200, 30);
        getContentPane().add(username_box);
        username_box.setBounds(550, 170, 160, 30);
        getContentPane().add(password_box);
        password_box.setBounds(550, 260, 160, 30);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(14, 20, 40, 30);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 420, 140, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagess/Update_member.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        index_5 in5=new index_5();
        in5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int x = JOptionPane.showConfirmDialog(null,"Confirm your update !");
        if(x == 0)
        {
            this.update_data();
            index_5 in5 = new index_5();
            in5.setVisible(true);
            this.dispose();        
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void f_name_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_f_name_boxKeyTyped
        char c = evt.getKeyChar();
        if(Character.isDigit(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_f_name_boxKeyTyped

    private void l_name_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l_name_boxKeyTyped
        char c = evt.getKeyChar();
        if(Character.isDigit(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_l_name_boxKeyTyped

    private void tele_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tele_boxKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(tele_box.getText().length() > 9){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tele_boxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField dob_box;
    private javax.swing.JTextField email_box;
    private javax.swing.JTextField f_name_box;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField l_name_box;
    private javax.swing.JPasswordField password_box;
    private javax.swing.JTextField tele_box;
    private javax.swing.JTextField username_box;
    // End of variables declaration//GEN-END:variables
}
