/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

//import AdminInterfaces.index_1;
import AdminInterfaces.Login_a;

/**
 *
 * @author Lenovo
 */
public class index extends javax.swing.JFrame {
    
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_icon_1 = new javax.swing.JLabel();
        admin_icon_2 = new javax.swing.JLabel();
        user_icon_1 = new javax.swing.JLabel();
        user_icon_2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        admin_icon_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_icon_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_icon_1MouseClicked(evt);
            }
        });
        getContentPane().add(admin_icon_1);
        admin_icon_1.setBounds(130, 120, 200, 130);

        admin_icon_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_icon_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_icon_2MouseClicked(evt);
            }
        });
        admin_icon_2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                admin_icon_2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(admin_icon_2);
        admin_icon_2.setBounds(170, 280, 120, 40);

        user_icon_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user_icon_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_icon_1MouseClicked(evt);
            }
        });
        getContentPane().add(user_icon_1);
        user_icon_1.setBounds(460, 120, 190, 130);

        user_icon_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user_icon_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_icon_2MouseClicked(evt);
            }
        });
        getContentPane().add(user_icon_2);
        user_icon_2.setBounds(500, 280, 110, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagess/Index.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 780, 500);

        setSize(new java.awt.Dimension(788, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_icon_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_icon_1MouseClicked

        Login_a log_1 = new Login_a();
        log_1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_admin_icon_1MouseClicked

    private void admin_icon_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_icon_2MouseClicked
 
        Login_a log_1 = new Login_a();
        log_1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_admin_icon_2MouseClicked

    private void user_icon_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_icon_2MouseClicked
        
        Login log_1 = new Login();
        log_1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_user_icon_2MouseClicked

    private void user_icon_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_icon_1MouseClicked

        Login log_1 = new Login();
        log_1.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_user_icon_1MouseClicked

    private void admin_icon_2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_admin_icon_2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_icon_2AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_icon_1;
    private javax.swing.JLabel admin_icon_2;
    private javax.swing.JLabel background;
    private javax.swing.JLabel user_icon_1;
    private javax.swing.JLabel user_icon_2;
    // End of variables declaration//GEN-END:variables
}
