/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Toshiba
 */
public class Loarding extends javax.swing.JFrame {

    
    private Timer t = null;
    private int count =0;
    
    
    public Loarding() {
      
        
        t = new Timer(100,new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            count++;
            jProgressBar1.setValue(count);
                 if(jProgressBar1.getValue()<100)
                 {
                  jProgressBar1.setValue(jProgressBar1.getValue()+1);
                  progress(jProgressBar1.getValue());
                 }
                 else
                 {
                   t.stop();
                   pro();
                 }
            }
        });
        t.start();
          initComponents();
          
    }
    
     private void pro(){
        
        index in1 = new index();
        in1.setVisible(true);
        this.dispose();
        
    }
     
      private void progress(int t){
 
        if(t < 20)
            progress_box.setText("Loading Modules . . . .");
        else if(t < 40)
            progress_box.setText("Verifying . . . .");
        else if(t < 60)
            progress_box.setText("Preparing . . . .");
        else if(t < 80)
        {
            progress_box.setText("Resolving . . . .");
            //com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.2f);
        }
        else 
            progress_box.setText("Initializing . . . .");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        progress_box = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(50, 340, 310, 17);
        getContentPane().add(progress_box);
        progress_box.setBounds(160, 360, 190, 12);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagess/topic.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 30, 370, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagess/IMG_7214_1.GIF"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loarding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loarding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loarding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loarding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loarding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel progress_box;
    // End of variables declaration//GEN-END:variables
}
