/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.KeyEvent;
import DBCONNECT.db_connect1;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import e.learning.member;
/**
 *
 * @author Toshiba
 */
public class profile_add_card extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    private String c_type;
    private String c_no;
    //private int pin;
    //private String mounth;
    member m1 = new member();
    
    public profile_add_card() {
        initComponents();
        con = db_connect1.connect();
        this.on_load();
    }
    
    private void on_load(){       
        
        ButtonGroup card = new ButtonGroup();
        card.add(jRadioButton1);
        card.add(jRadioButton2);
        card.add(jRadioButton3);
        
    }
    
    private void get_d(){
        
        String card_type = this.c_type;
        this.c_no = card_num_box.getText().toString();
        String cno = card_num_box.getText().toString();
        String pin = pin_box.getText().toString();
        String exp_m = mm_box.getSelectedItem().toString();
        String exp_y = yy_box.getSelectedItem().toString();
        
        if(card_type == null)
            JOptionPane.showConfirmDialog(null,"Select Card Type");
        else if(cno.equals(""))
            JOptionPane.showConfirmDialog(null,"Enter Card Number");
        else if(cno.length() != 16)
            JOptionPane.showConfirmDialog(null,"Check Your Card Number and Re-Enter it");
        else if(pin.equals(""))
            JOptionPane.showConfirmDialog(null,"Enter PIN Code");
        else if(pin.length() != 3)
            JOptionPane.showConfirmDialog(null,"Check Your PIN Code and Re-Enter it");
        else{
                String sql_11 = "SELECT COUNT(*) as tot FROM card_info WHERE mem_id = '"+m1.get_id()+"'";
                String sql = "UPDATE card_info SET ctype = '"+card_type+"',card_no = '"+cno+"',pin = '"+pin+"',exp_date = '"+(exp_m+"-"+exp_y)+"' WHERE mem_id = '"+m1.get_id()+"'";
                String sql_22 = "INSERT INTO card_info (mem_id,ctype,card_no,pin,exp_date) VALUES('"+m1.get_id()+"','"+card_type+"','"+c_no+"','"+pin+"','"+(exp_m+"-"+exp_y)+"')";
                try{
                   ps = con.prepareStatement(sql_11);
                   rs = ps.executeQuery(); 
                   rs.next();
                   int tot = Integer.parseInt(rs.getString("tot"));
                   
                   if(tot == 1)
                   {
                      try{
                          ps = con.prepareStatement(sql);
                          ps.execute(); 
                          
                      }
                      catch(Exception e){
                          System.out.println("Error to insert new Card info = "+e.getMessage());
                      } 
                   }
                   else
                   {
                      try{
                          ps = con.prepareStatement(sql_22);
                          ps.execute(); 
                          
                      }
                      catch(Exception e){
                          System.out.println("Error to insert new Card info record = "+e.getMessage());
                      }  
                   }
                   int x = JOptionPane.showConfirmDialog(null,"Card Renewal Completed !");
                   if(x == 0 || x == 1 || x == 2){
                    profile_update pu1 = new profile_update();
                    pu1.setVisible(true);
                    this.dispose();
                   }
                }
                catch(Exception e){
                    System.out.println("Error to find card Info. Error = "+e.getMessage());
                }

        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        card_num_box = new javax.swing.JTextField();
        pin_box = new javax.swing.JTextField();
        mm_box = new javax.swing.JComboBox();
        yy_box = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 530));
        getContentPane().setLayout(null);

        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(130, 170, 21, 21);

        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(390, 170, 21, 21);

        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(640, 170, 21, 21);

        card_num_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                card_num_boxKeyTyped(evt);
            }
        });
        getContentPane().add(card_num_box);
        card_num_box.setBounds(60, 280, 190, 30);

        pin_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pin_boxKeyTyped(evt);
            }
        });
        getContentPane().add(pin_box);
        pin_box.setBounds(60, 360, 190, 30);

        mm_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(mm_box);
        mm_box.setBounds(440, 360, 60, 30);

        yy_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26" }));
        getContentPane().add(yy_box);
        yy_box.setBounds(500, 360, 70, 30);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 40, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 450, 60, 20);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 420, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagess/payment.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        this.c_type="VISA";
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        this.c_type="MASTER";
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        this.c_type="AMEX";
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void card_num_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_card_num_boxKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(card_num_box.getText().length() > 15){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_card_num_boxKeyTyped

    private void pin_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pin_boxKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(pin_box.getText().length() > 2){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pin_boxKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        profile_update pu=new profile_update();
        pu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        index in=new index();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.get_d();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile_add_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile_add_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile_add_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile_add_card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile_add_card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField card_num_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JComboBox mm_box;
    private javax.swing.JTextField pin_box;
    private javax.swing.JComboBox yy_box;
    // End of variables declaration//GEN-END:variables
}
